# Generated by Django 4.2.5 on 2023-10-16 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_historia_receta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Historia',
            new_name='Historial',
        ),
    ]
