# Generated by Django 4.2.5 on 2023-10-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_historia_historial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cesfam',
            name='id',
        ),
        migrations.RemoveField(
            model_name='despacho',
            name='id',
        ),
        migrations.RemoveField(
            model_name='historial',
            name='id',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='id',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AlterField(
            model_name='cesfam',
            name='id_cesfam',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='id_despacho',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historial',
            name='id_historial',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rut',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='receta',
            name='folio',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
